### PR TITLE
[PAN-1597] upgrade mongodb version - dbstream-mongo repo

### PR DESCRIPTION
**Pull request by OmriGLevy**
Jira Issue: [PAN-1597](https://panoply.atlassian.net/browse/PAN-1597)

## Description
Mongo 4.2 is almost out of maintenance, therefore our cluster will be automatically upgraded  to the next version (4.4).
We need to upgrade our mongo to be able to run on newer cluster version.

## Upgraded
mongodb@3.1.1 --> mongodb@5.1.0

## Tested on 
Mongo community@4.2
Mongo community@5.0

[PAN-1597]: https://panoply.atlassian.net/browse/PAN-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by OmriGLevy** [comment]
@eladon I can not set reviewers or assignee

**Comment by eladon** [comment]
@OmriGLevy probably some permissions issue

**Review by german-panoply — APPROVED** [review]

**Comment by yonivy** [comment]
> @eladon I can not set reviewers or assignee

@OmriGLevy Fixed.

**Comment by yonivy** [comment]
@OmriGLevy there are no automated checks for this repo. Did you run `npm test`? is it passing?

**Comment by yonivy** [comment]
@OmriGLevy please scan the panoply codebase for the term `dbstream`. I accidentally found a comment mentioning `dbstream-mongo` and a caveat about it using an old mongodb driver, which obviously cannot remain in the codebase anymore.

**Comment by yonivy** [comment]
@OmriGLevy I found something suspicious after skimming the [mongo v5 migration guide](https://github.com/mongodb/node-mongodb-native/blob/HEAD/etc/notes/CHANGES_5.0.0.md#collectioninsert-collectionupdate-and-collectionremove-removed). I see that the `remove` method was removed but I see `collection.remove()` being used in https://github.com/panoplyio/dbstream-mongo/blob/master/mongo.js#L65

Did you review the deprecations both here and in the panoply codebase?

**Comment by OmriGLevy** [comment]
> @OmriGLevy there are no automated checks for this repo. Did you run `npm test`? is it passing?

Yes it passed all of the tests

**Comment by OmriGLevy** [comment]
> @OmriGLevy I found something suspicious after skimming the [mongo v5 migration guide](https://github.com/mongodb/node-mongodb-native/blob/HEAD/etc/notes/CHANGES_5.0.0.md#collectioninsert-collectionupdate-and-collectionremove-removed). I see that the `remove` method was removed but I see `collection.remove()` being used in https://github.com/panoplyio/dbstream-mongo/blob/master/mongo.js#L65
> 
> Did you review the deprecations both here and in the panoply codebase?

Yes it is suspicious however it did not seem to effect anything, I tested collect, delete tables, signup and sign in, workbench query, export. and everything works fine, do you have any idea how to specifically test this ?

**Comment by yonivy** [comment]
@OmriGLevy yes, through the magic of "unit tests" 🌈

**Comment by OmriGLevy** [comment]
> @OmriGLevy yes, through the magic of "unit tests" 🌈

It passed all of the unit tests in both repos,

**Pull request merged**
